<?xml version="1.0"?>
<robot name="edumip_my_robot"  xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="wheel_separation" value="0.070" /> 
  <xacro:property name="wheel_radius"     value="0.034" /> 
  <xacro:property name="wheel_width"      value="0.010" />
  <xacro:property name="body_height"      value="0.1"   /> 
  <xacro:property name="body_width"       value="0.050" /> 
  <xacro:property name="body_length"      value="0.035" />
  <xacro:property name="pii"              value="3.1415"/>

  <material name="blue">
    <color rgba="0 0 0.8 .5"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 .5"/>
  </material>

  <link name="edumip_body">
    <visual>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <link name="wheelL">
    <visual>
      <origin rpy="${pii/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="jointL" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="edumip_body"/>
    <child link="wheelL"/>
    <origin rpy="0 0 0" xyz="-0.025 ${wheel_separation * 0.5} 0.0"/>
  </joint>

  <link name="wheelR">
    <visual>
      <origin rpy="${pii/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>  

  <joint name="jointR" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="edumip_body"/>
    <child link="wheelR"/>
    <origin rpy="0 0 0" xyz="-0.025 ${-wheel_separation * 0.5} 0.0"/>
  </joint>

  <link name="stripeL">
    <visual>
      <origin rpy="${pii/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.005 ${wheel_radius*2} 0.005"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="stripe_jointL" type="fixed">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="wheelL"/>
    <child link="stripeL"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
  </joint>

</robot>
